-- AlterTable
ALTER TABLE "Tenant" ALTER COLUMN "domain" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "plan" TEXT NOT NULL DEFAULT 'basic';
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "isDefault" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Tenant" ADD COLUMN IF NOT EXISTS "isActive" BOOLEAN NOT NULL DEFAULT true;
