"""initial schema

Revision ID: fccec8ed9d23
Revises: 
Create Date: 2026-02-09 10:30:04.345700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = 'fccec8ed9d23'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('career_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('career_titles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_titles_id'), 'career_titles', ['id'], unique=False)
    op.create_index(op.f('ix_career_titles_title'), 'career_titles', ['title'], unique=True)
    op.create_table('careers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('career_type', sa.String(), nullable=True),
    sa.Column('min_cost', sa.Float(), nullable=True),
    sa.Column('avg_cost', sa.Float(), nullable=True),
    sa.Column('high_cost', sa.Float(), nullable=True),
    sa.Column('has_scholarship_options', sa.Boolean(), nullable=True),
    sa.Column('avg_salary', sa.Float(), nullable=True),
    sa.Column('riasec_vec', Vector(dim=6), nullable=True),
    sa.Column('ocean_vec', Vector(dim=5), nullable=True),
    sa.Column('profile_vec', Vector(dim=11), nullable=True),
    sa.Column('aptitude_vec', Vector(dim=5), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['career_categories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_careers_career_type'), 'careers', ['career_type'], unique=False)
    op.create_index(op.f('ix_careers_category_id'), 'careers', ['category_id'], unique=False)
    op.create_index(op.f('ix_careers_id'), 'careers', ['id'], unique=False)
    op.create_index('ix_careers_ocean_vec_cos', 'careers', ['ocean_vec'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'ocean_vec': 'vector_cosine_ops'})
    op.create_index('ix_careers_profile_vec_cos', 'careers', ['profile_vec'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'profile_vec': 'vector_cosine_ops'})
    op.create_index('ix_careers_riasec_vec_cos', 'careers', ['riasec_vec'], unique=False, postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'riasec_vec': 'vector_cosine_ops'})
    op.create_table('category_ideal_profiles',
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('ocean_vec', Vector(dim=5), nullable=False),
    sa.Column('riasec_vec', Vector(dim=6), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['career_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('category_id')
    )
    op.create_table('career_eligibility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('education_level', sa.String(), nullable=False),
    sa.Column('stream', sa.String(), nullable=True),
    sa.Column('degree', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_eligibility_id'), 'career_eligibility', ['id'], unique=False)
    op.create_table('career_paths',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_paths_id'), 'career_paths', ['id'], unique=False)
    op.create_table('career_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['career_id'], ['careers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('career_id', 'language', name='uq_career_lang')
    )
    op.create_index(op.f('ix_career_translations_id'), 'career_translations', ['id'], unique=False)
    op.create_table('career_path_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('path_id', 'language', name='uq_path_lang')
    )
    op.create_index(op.f('ix_career_path_translations_id'), 'career_path_translations', ['id'], unique=False)
    op.create_table('career_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path_id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('duration_years', sa.Float(), nullable=True),
    sa.Column('cost_range', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['path_id'], ['career_paths.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_career_steps_id'), 'career_steps', ['id'], unique=False)
    op.create_table('career_step_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['career_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('step_id', 'language', name='uq_step_lang')
    )
    op.create_index(op.f('ix_career_step_translations_id'), 'career_step_translations', ['id'], unique=False)
    op.create_table('scholarships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('coverage', sa.Text(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['step_id'], ['career_steps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scholarships_id'), 'scholarships', ['id'], unique=False)
    op.create_table('scholarship_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scholarship_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('eligibility', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['scholarship_id'], ['scholarships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scholarship_id', 'language', name='uq_scholarship_lang')
    )
    op.create_index(op.f('ix_scholarship_translations_id'), 'scholarship_translations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scholarship_translations_id'), table_name='scholarship_translations')
    op.drop_table('scholarship_translations')
    op.drop_index(op.f('ix_scholarships_id'), table_name='scholarships')
    op.drop_table('scholarships')
    op.drop_index(op.f('ix_career_step_translations_id'), table_name='career_step_translations')
    op.drop_table('career_step_translations')
    op.drop_index(op.f('ix_career_steps_id'), table_name='career_steps')
    op.drop_table('career_steps')
    op.drop_index(op.f('ix_career_path_translations_id'), table_name='career_path_translations')
    op.drop_table('career_path_translations')
    op.drop_index(op.f('ix_career_translations_id'), table_name='career_translations')
    op.drop_table('career_translations')
    op.drop_index(op.f('ix_career_paths_id'), table_name='career_paths')
    op.drop_table('career_paths')
    op.drop_index(op.f('ix_career_eligibility_id'), table_name='career_eligibility')
    op.drop_table('career_eligibility')
    op.drop_table('category_ideal_profiles')
    op.drop_index('ix_careers_riasec_vec_cos', table_name='careers', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'riasec_vec': 'vector_cosine_ops'})
    op.drop_index('ix_careers_profile_vec_cos', table_name='careers', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'profile_vec': 'vector_cosine_ops'})
    op.drop_index('ix_careers_ocean_vec_cos', table_name='careers', postgresql_using='ivfflat', postgresql_with={'lists': 100}, postgresql_ops={'ocean_vec': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_careers_id'), table_name='careers')
    op.drop_index(op.f('ix_careers_category_id'), table_name='careers')
    op.drop_index(op.f('ix_careers_career_type'), table_name='careers')
    op.drop_table('careers')
    op.drop_index(op.f('ix_career_titles_title'), table_name='career_titles')
    op.drop_index(op.f('ix_career_titles_id'), table_name='career_titles')
    op.drop_table('career_titles')
    op.drop_table('career_categories')
    # ### end Alembic commands ###
